# Generated by Django 5.1.6 on 2025-03-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['producto_nombre'], 'permissions': [('poder_agregar_productos', 'Puede usar crud productos')]},
        ),
    ]
