# Generated by Django 5.1.6 on 2025-03-06 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('comprado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_comprado_user', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos_app.productos')),
            ],
        ),
    ]
